// Global using directives

global using System.Collections.Concurrent;
global using System.Collections.Frozen;
global using System.Collections.Immutable;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.Json.Serialization.Metadata;
global using System.Xml.Serialization;
global using IronPython.Hosting;
global using IronPython.Runtime.Exceptions;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Scripting;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Microsoft.CodeAnalysis.Scripting;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.Scripting.Hosting;
global using SharpCompress.Archives;
global using SharpCompress.Archives.Tar;
global using SharpCompress.Common;
global using SharpCompress.Compressors;
global using SharpCompress.Compressors.BZip2;
global using SharpCompress.Writers;
global using SharpCompress.Writers.Tar;
global using ZaggyCode.Core.Archiving.Interfaces;
global using ZaggyCode.Core.Archiving.Model;
global using ZaggyCode.Core.Common;
global using ZaggyCode.Core.Common.Utils;
global using ZaggyCode.Core.Data.Interfaces;
global using ZaggyCode.Core.Data.Model;
global using IUserStorage = ZaggyCode.Core.Data.Interfaces.IObservableStorage<ZaggyCode.Core.Data.Model.UserData>;
global using IPythonSettingsStorage = ZaggyCode.Core.Data.Interfaces.IObservableStorage<ZaggyCode.Core.Data.Model.PythonSettings>;
global using ZaggyCode.Core.Factories;
global using ZaggyCode.Core.Game.Enums;
global using ZaggyCode.Core.Game.EventArgs;
global using ZaggyCode.Core.Game.Interfaces;
global using ZaggyCode.Core.Game.Models;
global using ZaggyCode.Core.Languages.Attributes;
global using ZaggyCode.Core.Languages.Enums;
global using ZaggyCode.Core.Languages.EventArgs;
global using ZaggyCode.Core.Languages.Interfaces;
global using ZaggyCode.Modules.Archiving.Options;
global using ZaggyCode.Modules.Data;
global using ZaggyCode.Modules.Data.Json;
global using ZaggyCode.Modules.Data.Options;
global using ZaggyCode.Modules.Game;
global using ZaggyCode.Modules.HostedServices.Options;
global using ZaggyCode.Modules.Languages.Options;
global using ZaggyCode.Modules.Languages.Validation;
global using GameModel = ZaggyCode.Core.Game.Models.Game;
global using Language = ZaggyCode.Core.Languages.Enums.Language;
global using SyntaxNode = Microsoft.CodeAnalysis.SyntaxNode;
