<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <WarningsAsErrors>true</WarningsAsErrors>
        <ImplicitUsings>enable</ImplicitUsings>
        <ApplicationIcon>Assets/logo.ico</ApplicationIcon>
        <PreserveCompilationContext>true</PreserveCompilationContext>

        <AssemblyName>ZaggyCode</AssemblyName>
        <AssemblyTitle>Zaggy's Code</AssemblyTitle>
        <AssemblyDescription>Редактор кода для обучения программированию</AssemblyDescription>
        <Version>2026.0.0</Version>
        <Company>Zaggy's Code Project</Company>
        <Authors>Morozov Makar (TheMakarik)</Authors>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <OutputType>Exe</OutputType>
        <DisableWinExeOutputInference>false</DisableWinExeOutputInference>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <OutputType>WinExe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="Assets\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.1" />
        <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
        <PackageReference Include="Avalonia.Wayland" Version="12.1.1" />
        <PackageReference Include="AvaloniaEdit.TextMate" Version="12.0.0" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Declarative.Avalonia.AgentTools" Version="12.1.1" Condition="'$(Configuration)' == 'Debug'" />
        <PackageReference Include="DynamicData" Version="9.4.33" />
        <PackageReference Include="Material.Icons.Avalonia" Version="3.0.2" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.9" />
        <PackageReference Include="Scrutor" Version="7.0.0" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="12.1.1" />
        <PackageReference Include="ReactiveUI.SourceGenerators" Version="3.2.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog" Version="4.3.1" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
        <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.17" />
        <PackageReference Include="System.Reactive" Version="7.0.0" />
        <PackageReference Include="VirtualTerminal.Avalonia" Version="1.10.0" />
        <PackageReference Include="Xaml.Behaviors.Interactivity" Version="12.0.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ZaggyCode.Modules\ZaggyCode.Modules.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PythonStdLib Include="$(NuGetPackageRoot)ironpython.stdlib\3.4.2\contentFiles\any\any\lib\**\*.*" />
    </ItemGroup>

    <Target Name="CopyPythonLibToOutput" BeforeTargets="Build">
        <Copy SourceFiles="@(PythonStdLib)" DestinationFiles="@(PythonStdLib->'$(OutputPath)Languages\Python\Lib\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    </Target>

    <Target Name="CopyPythonLibToPublish" AfterTargets="Publish">
        <Copy SourceFiles="@(PythonStdLib)" DestinationFiles="@(PythonStdLib->'$(PublishDir)Languages\Python\Lib\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    </Target>

    <ItemGroup>
        <None Remove="appsettings.json" />
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
        <Compile Remove="Assets\CodeExamples\*.cs" />
        <Content Include="Assets\CodeExamples\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
        <Content Include="Themes\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Views\Converters\" />
    </ItemGroup>
    
</Project>